apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: observability
  source:
    repoURL: git@github.com:n0n3m4s/riverrise-ops.git
    targetRevision: main
    path: charts/wrappers/monitoring
    helm:
      releaseName: monitoring
      valueFiles:
        - ../../../environments/prod/values/monitoring.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
