---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: ghcr-pull
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgB+rK1pCGZZ35pd8m6UY4m/XcUyOZFVr4p8FcKs+k50HilQ3+M9BX080arFQrmPGxU/bb/nCFB80eFYxSNKJbBOc7WVvfM8Ry0CbrJwxXCO/6b2rZoyEHuScNiZlwHCdHT6M9JXFqRPQ2VesCz5dPHkbb035GDVUGKVRDyZaXCcai5sYMZMCm+ZKslAyizd/zul5BnHf3pN1cq1IxutnYUTAzTGbjFZICbKsM56o4WKh40zaLgwZmS7XnkfECon8W4IHHb/l68ILaT8GYF1cnBEICjN/QrIdJfX9cEKevBSQm7YkgU0+7YxVy6pWmhoqLiyEULuzb0g/e5xrwj0da6tk7Yqkj+sTYRNJnDfwrviIyuoI5zL+j4Wxjfdt908eOC0Ze6D/R4cwHsiUhT6JeLDDtmk1MCOrC14TP/6OWJIeSCjoynOMRYEfRwRPiSdCszwyLvbnhHsEwr664gOHvre4/lmS362jDBDu9iKCZBG81nqqq0I79CaS+j3bpUJFKdqz7oF0B+n0WSzPEgqIHq98QykrLBrUlnlBTEd0Oyz5CKB19RH+yRcfDMZTI7UtJX4gJ8o20jmuLNKbR5y1Lb3HNRDEmSgPZWYcpXajgQGESDsCeFeV1Filba9I/WzE5d2R1aCWG1NgZsU/Qhj0YA9nqyjA3qVVvlaDZBpZCz7lbDSE1cSeOfouSQMiQufKJPLpzMT//VRhYDA9Iql1Pl/K+JkH2wAj64VX4brtf5dnrv08mMcglYUtHXU+HLLie7Rm15PHsanW1yPXU3ep8Wf7zf2rXhKrGvYEHyAMOMXY5cSb/J+R8kprJGy/Miza+J9ztiVBYc/VsXQh4MCL6laxDvWvC7BdEjr8EDwO9t50y4s3l8oSrzdsy24xku8XPauBrsFr9N/X3hJdHGVS5Ixi56pDG8zVT3R4+G48f32Gz7INeDoLVTJ9MmQdCJ9tPwb7Mvy4YT4Mzlxu+18Tjn8OKqZ3WgQZrg=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      name: ghcr-pull
      namespace: default
    type: kubernetes.io/dockerconfigjson
