---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDNwHWw/urimn/KC5DljsGPiyap25Iu+iQKx3P7cIEXgZeZXUpGkQaLHg2+yj/M4MQma6rOLyMJm6FPaZn+fnaI2cLWzgxDhgm4B9ErflKibApBUuoEQTKzVrQHwZnNGtrFDajES8Q0LRxHjLHPt7wEQhQZ002VP6zPWd9P1Lc5jrZBga1FCiIo41wtwaGf7mkzNPH5r0r/PdcSlEwXWXVWuIrvDQpo/V2/pyFcfA6Lz/vcO8z+Ms76oKDp5lEqajz3JNI4geBTAqoMVGgN1eNNmhSu2/aRd2/m/EWY9mRMCkiqFK+KZoWxns1LzdW6jle75SnbSKBOFWZeREv1Bq0eJ1cNeAsYyFbmmobLEkXHOqvyLlHKd/FGjn4tsEiNeYVbUN+yVDUpQsj9K1UbmKfoH8JGwoELC7wbUiyl5ae+pPT3heva0i7TInDQkg8C+8zOkSvsSUeeMEfKyGe1x7H8LWksvfX6GnGTBquMrgptog3uI5GP2PBDIcngOrF45mqmFj9TuDFfniqPDbm+qFUt8NOXiSPEWVI6NVNt4d1uax3maZ39ck/WHde5lFYNE1/EjXbrErchUkvmEwpjjy1Z5X+xWUGy5RlM2E6THdZj68KS9FKK7NN574K5pypDXuan8xNUl3e7WtgURuxgg0ICPnZgNW7WFvAyZYWKUSRQGIwtBZs+cQVN06p4pbQ+Iog+BNsXq68Fd3/XMBSkLpQJM9OdBRrrMGM=
    admin-user: AgBHTtMn4G9CewuszO2zp4uMO3wBw+SWxqfnSCypjj74MfuCt+YVbSwZzuHGbb3BPRslx8zWHTk9On2J2WStvy4FcEoF0xYuOfJJjfLGrlKGOAT16cptVoRz7WQEOSh9kyp04n3RjIhnAnn5u4bYrE2/R6tOK18nqQvLBoEBYVpfNIsZaGBtDpOyiM5nZ4JNwEJa/wYiScPxaU2NKewSVmgLgFfz4zXH8MVj2SJ5qFStzsravqX56Hl3ifZSITyY7fsASQp9gdrzhpj7mnFJbnZBwjC6KwRTnaYk4s9I8BsAuJ8SiUEJfq3YDhebk+fog7262tBnEGTEWPauqnqBVBn4SvniLLAKXK4kJhf41XY1DkQmA2xp+hg2+ZoPzBAvYynkp6q3/5MHjuNUH8KaOaQ8PJGdGb0Azs34L7dDDej11VnKRjBZpgYWUTpX0n8BOiyVVn1uVP4YZ7WTe+2WFgqGdKx9wxF5kgd4ZoIHr3W28tweO+znH8ijTWY7zOKFxcy4PsgeEg/aCLp38VA83589LgrrIPaIGsFNfS6K1xbbbasHElPsegCzyDguFqdWG2DHOfzPMRtc8udiU6+Ljw+NJxenMqPP5f2npvub2IQMMkqrIO5d2+A3pLZCEM6G2rRvRv+i0KP8w7DfeRwz9kB60X0oxRSEPnOY43U+CEAphQcBUdgLTYz/EantpA35QuuUJyTwXw==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      name: grafana-admin
      namespace: monitoring
    type: Opaque
