---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: rabbitmq-auth
  namespace: databases
spec:
  encryptedData:
    erlang-cookie: AgA7Eev8qGrekz8cLLcGttGLNDUTnI23I4D6PVV3eMxI0na0tyl/tF54PlfLk4eKUvK2+OcLTrjFkRWFvs9U6odq0m7096oxG6p9RPdquKb36MHD9zhE9GiiuwVNkXUgL6Z4onIBC1hwEbVSnQICWZleoMeOm7mnOI0uy9MdymFWOsKmaxugIwSGrdveMTHuR767/I/XNq6RJPqhTyxqcjPYXYLVvFtTdxuiXWrcftE1ydhl9UkTbwd8hPxyrDZr8ZBquTzUUPxrsDiTpzwgLqj2fq9BtmInVxiOq9XqFAix476sRt0omh1SWR0NeRBa8UJNabkHTMU2K7g1JPZROK4M0QZoYb36kAmKd/Z/uWQS0oqF+El4TVxMuEPI53fD+T5DNn0nNN65FO/9Tq/s8QQLuX/MXs06SP9qtKuW2bz/4Ugdlh7K0kSNlWRQ2xu4Vb9F2fa6vpbQ4kp5iSMJNz89OwujBvmNR23O4thPznTUemiFsKUkmJzdmji+8yNqRgkFfw221uxJ1zI98xmcuQRLok+Ao/guJUR3ZyijtDwVLhgjd0hW360ABeab6Sxqxfw1FlaXPFLOsfeZ6opth28spj+0erXILbf0A0tHohpzuWfxsFBFv0CT81BIEMecguD6jR5CeHM1Me3eYQG1k9X3Gfzw9jpCGtvl/ZAIlGDSO73Lh2J+Yvqgk2S7LNlwPhJQvhJyc5F2xiWc6W3qRBYh3JjMk10o5SP2/j20oakecTl7eiF2ueGyOribOgbSL3RmM4hZT/baC9Zdg26XYFiI
    password: AgAta+eXfafxspHFyYt0bf2oa1gpOEbayVAHbq3urkUbOLDJ4XJfILm8epwr12B23k8tCIvTP+34ObAX8PsldUkgtSUW7Jfg+dJ29EJPeqT8X7HBZN4l/ZvRxOBItwUePRNxDTyrVfYXI19Z7ms2MHeFftL5t3wwP3db0QdBPrxRFCzxgR2woMmBDAMEWF5hM8sRVidKb2iu4/93D8j1zM3iKQSgcEPiqM8wRZ4SRivx84cl/gECO4Bv6HA9mE+kU/lrzCG/SHmbihE4RgXDowjJQs3G9h5r9qFTEJwnKhQzCqwlOuxCFp9icLIWEmR4TXDtKMQZoNP7CNg+UQ0bNFzidcluustc4Np/jio3VrlY+PVuCiCKflR18yjBJxg7Dv/ygTI0EtZv3Cs0mddo80apDaZBdStHR/RA7aDM7lJ7Ta1nlxFiBjFBvMtccyFVfRcWVkoc1EpW1mLuDti0R2zrDL0A9WRhs65arW8hr4snl4+qfg6dOtvWenhf5cucaaxjOiriMPAJctupWvXQIxkdh7dyopP0VVm3fU2tjVgJ0Yzudfc4K8M5gu7INhkxh379yRBw0+5Ev4wjc0wHE+G0jNcthaIXPz915g84UxR4ECyLtzZ3o88F+kPVKxU0szCgXQpTS4LVzfVfR1aidlUV8a7I5/FHgJn08Et1LfYRQOk/Wl71tFiqEBkqXXBMlTZ2B8Wodo1S6PfkJMBhziha6gxyMtBXq3RJzjulOfSdBg==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      name: rabbitmq-auth
      namespace: databases
    type: Opaque
