---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: ghcr-pull
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAeuNelpb9C02vGI41GaMW6Xt9PC73SOkLG2hD8GuiCNAjoWmSbSwsb5fzv9FNhmLM1dgX+vX2vQ5bTcBS0Qv3uMOcTSeRx9RH4h94pLiZUlyqFG0EpGYK6GmFZWlVZDx8ikGzakPT97p2cdB1Kxww/UZGiM3ZX5fS4mzk4eECyxxeq4IQ7A06NqmBubNElwCUPWjBCQFFhfylocAbRRxwEk5sfnj0wPc5hUDbSGeGPxHmzQPdYL0nJOiucvfrm1wiJTamLv9BE80uYPD8VzL90KgYhu19j+xb01+4cfifpD5oGS/+3FROcTalBcYrhUI0dvoNM9PRpwPl1XwuEEswE/c7cdSkXTMmG6Wq1p9X8HKbXtmZ999T/5Aa2NVzts/lMeCG8UFq2AbNbaydg6h90rY81zq3JDr3hPkKQ2UCQStWS8CwelQGlk6gqZ5vtv2JySLBkOBAvQkzIvwehc/mJfnNX7OvK6fWGhrF3PMIMAlHBiYnB932Mbo2pdi2+MZ/V1RUuZNFg5KRKl6uZlCgFAeYZzzl0UsyhO9YbRyxdMcd9Iew5NLM4Jprmse2jlc5uAeacewQiXDalds2estUpsbiiNFiynXXqst3yt37wYgEIqfRb1trYu2/CAltjZQ8QPgDAkDJTBADMKkqACeSSWzpBMbpknaRXMs3eO0/n8vpUDluSHgU1fbW7gZ4V0s/Nqkvp9TcWNXzgQmty+hS3xrF8+VnsoKm/bDElRDGgTlUAQ6foVXgW5Lr8jLHPnRuPwS6cI51AOlLvrIvfvCk0myzBvi1AIFDLPxnWcNiPwm/8dyoIUVxxTSMxyQpWaDSoRtYDojA/zitHIXnnCtxReFbMltsV2Q9V0aYSZE0WEOU7AS2a/b51xANP44W937JoCMZ/c5/BGf+uPtyyXV8FfGYMge0kamOhnciEeTXSQrS4b541n6pr50IReDTCFZItzjdOQ/6WWfoWKapdEUn6RFJFdpv6eSQ=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      name: ghcr-pull
      namespace: default
    type: kubernetes.io/dockerconfigjson
