---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBEzT3nRiw/01CdILdCyd46ADBiuxFV6J6iOtFE+Y+Qcsz4y66nvTSpau+8SJtr29KL4XsFMbSZ/qx+ZZAnZXf1UqG6S4SEySxuJdHlyni8fOUvGD5pQkT9NldEdKsBvzbl6B7xHmAbIuD2H+EvUAci06OvPhF2FIN+E/it+kOk2RSkap8HigI77ln/UDRm3XJ1H6IgTOG+Chfo3tOXVGW2jv+bd8gkERFRfjaRM9ihWw682FnYLXApn3ex8W4WIDj3sL8UUXfkl18brWgQ2EL0PfZ2V5yV4II4tPjJ5ONVomPLOOy7ItB4ib/pW+hItg20R2r0Gm1R35ret5DIFDIjm8K51B1Ti51V3gbdWtDD58bK9K5D7YOI7UfK/RDAHo1ZxoqI4lapVA7tzvP1OdOFYSIvUzRHx4dOoZT6kqyv9rDSl6NYnKnnyXy7hWQe1s08BUvcQ3AH/EKjqHsQ+vicZz+Oq3XOfV43qJ5JAGFFzdq7ZHW06fExCHq0tFIfiOsdYl73On/UzL0m0c+zmHKKXNSNdOvhSbVfPVaGtVTKiOrv/sOyTDjIeNyNuxWq18IVwldn4En2cC1TaTGLeNE6j5QzNseEbdS6hIE7D+BOCmJdt3dN8fQQWuGv4fE1gZwiKSaPuoifu6plZru+mhVnmxVFhu9NQJqZ/3izTYps8BDlOmiIKsKu3+aECoNb4cg6ClKBr/ghhcW7Fiwtkb7+SyVDHp9fBLY=
    admin-user: AgB47n9IDuJbDAhC5Kr1XWgQfUnoWjhYNrxnQcIEs/HoLbUQ5HhorAvQrVVUJufkgol5V1DRW5I1XZ4IYnony4MyixlLEDhi+EGv1HWfKSgRA7BT3ro3+PcYL6QWBB3IkSdtbgvMwwYhgikth+o+jXzOvrMo0r61VGXyNH1lNa6ftW4XwWQ0RNndYKpWT0+74BIUPQRoq8qBc7rrOCsKr2XWGauTSd3PYAIo9eo04ZBjb7SsvaroF5xEhK6zjoFYD7DNZh1+KxmHWCN/A+rBKRRhpnfv5eJFw3eVMnmYlTYbs2rTfy14Le/N2Suss7k9kK2PI43bp3EuxFqDHfnXHFdWWRjoeLO5vFRpsYqhLCBgG++lJtshXjrq6/kak0KWPERvw3A/h8pfDmhRN5tby6tOrvhQ5VbQU2nkn8rsETUoO1ZBPPWLYwoSeEn9oLofq/LexymuTndk8SNpeCunELmvtweB1C3lqm45U968Cmlud9WcqLbwHI7Nrgk+Ce/8DtAKYPIjxS9oe30epOHvf6Z+AEePVCfs0XEi1ZkgbIViXL1PQjqwSE7mklqrrkCCV0MYB186+pS2kgLeNZ3f1do389vRc/iX2fgqVqZFvE6jH/68a3KXrjJCYefdZax+7DyMYWUTVmZaTHjeboviCVLECOzRY/hyBgLiM+tfWV+T/rH1e0IlBRUQRWUDlEF3I3Z9XIlYgA==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      name: grafana-admin
      namespace: monitoring
    type: Opaque
