---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: rabbitmq-auth
  namespace: databases
spec:
  encryptedData:
    erlang-cookie: AgAHEOP+Mq3aue7NLN0AYLYRwAz4ez4zDRkG1urq8XfP4YYmtQuKLDdCXqI+7Jf4t8gQb00eaP60kJAJIjLxh+1vMII4nubHa6BQy4Ce+LLR/bZIXyUbMOUzGGWG9YT+21nlUZ3Q7eITpRlr6gyuFrp30uurwrul56ZwuXgR4Zfp4dIOpn249Gi0bgVsB1aW000DqIkaUL89lFzPOMchhZ6GImHCtRl2Ocbq9XtgolXIewxRwls3J/Q9QjybIQob3eA+hz4qNova7bppnEbn3bR4SnVoN4GAJGueSuCUqeCaVb8TJvlHAaAxl0MzmHYdjUAAcZM04arCXe/wYtZ3xmT/u1+6V46Id2TKqQQQXM6PtwBY1jaBhsRu8nyxy8XPxueNirCB4Gemz+b5/WnSrJsjSI1qzKH1ydT1zCY6NuBcipatIS+SbLQOzUQo2sA1Hxd98Wxrr3+vZHlfIRUZrM0L59+5rK2x24wNTpmySocORONxfWU9z/uIfU9mYJ9YrMFt6HXXNTQrq6F3L5Uakcym8ozSHrKQuZExT53tQsuW8XhQl6XsuD0TZBzbilHf6qxF/yaJQybA1zkzSgtIAoSfoIyPw5mk5KV0WOrew6wxFJAJDe9y2MXPJGyB70mXuAxu62+uAlQ4IOXq2lsBwh1DfYZlZ0FZQvipN9TE+WCVVZulWupSQmbWuUzTaxU13EcWTg8cmsur3/S87V/+a87Iy7yNo61xFxPioWnOKuKm4yWER7ICkc/2je6q4FlEd+II1kYcehDst738ah6zi6jQ
    password: AgBJkXexDuhqQi1KmKIodBQaR3kzUyDWeB7wg1iJ9zkJQzeIO96Scr6dV8Z1tCjnIwT4pNnXSoosl4wfu5cW4ATrGEBgscGJv5y2dVDXi/qe9vajf/raXM3Dw6d5vdyt5yHBtRcbYUQZCSAdgq+fMyG5mkNpsKzhcYwnKWaLlkqm5mHrsqJRBeHHb58wmtDiW8oIQKRtcLepGnfMKbFsBM+QTM1d4rdnKMOpvaiSx6vphbOos/p8YMJPr8AVpEt3cZtbhSjUha0knUvXdCjKf5qgKnn2l4QgLHt3ic5liYO69a5Yz5OjpGtVX7qWi1pJY+t0VTlf//6JaAV1LVXcKl9N3tPsFzNRvYByjO6WNx1azQ5evsDArbVkAKE7HGspCY1WHM+L1b9uQdXvw5iFqiG2HzydBeZQP82QJQ5Yrrq10+jl4QkJy9VJZEy6GQExO9EFNRP1vlJF1o/8Qd06PXTv4Xhdtgi4/dx/RmS46czQ60erEmanuu2JHsI19ynygGfXg1CQchX1Rf39ZczpU/9WlNW3zVOSIBRHPxwFClhtgEveQbKDOurXLHax+Mlsef9aLh6IEmSUXBka+VnfRn8fd8F2lS1Q0MIxsh7OeZf+ZMSyYWejCQu4vBPctJQvlojBwocfno1hBt66B9vNONasHFmGofD6Eo+7qsLRNTYp/v+hpr6HndyaA+Fv93B1kXJQJEoW2u23eNGzbsSbzkXozdjlqvNyxeD4LDW4tWg5uQ==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      name: rabbitmq-auth
      namespace: databases
    type: Opaque
