---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: redis-auth
  namespace: databases
spec:
  encryptedData:
    redis-password: AgDolfz5NMq72++ti805lhSKzoIMmAaLm0rhR+Ek1u8Fi798J2CwDDtJAH9ieXmGVdmkiHGFPdSCV79QqGwRImwEIxfgUeiQ5WW4xLTmLeZs/J7WRu1YPFlFBBEHQzpmNZ/2cJt8gFe0/t1+2wks5DGY1fT3BlXU2odWhhdj8v4Iud+gOhc53L9cZXA+FM5zaTRpYsK699oYYISEQDfi/3sxjaCiyyOi1yIYjZhTr65a+nRjaMwn+hlQNxA37qCkuQi8MFRsx+lkUT9Fbv2IWiZJtqaMGa79PgdEE9BVdapKTys0fMxYy1d/qHtapFXUUu3ZxDlmn0oJPaGbY8cVb61tf4Po3H2Cgad2Bqv7mTPqlE4T5A8qbJW5SeC1q9waDvP+ezk87/kseq05PCwh0cH0fY+IkofVG8Uofc2CxJwO8WiDhH1Swghzzx8RG9n+UDYHl2MFk7X1R1odHCFwcEcToG47RSaE8kk3oFlodXmRQFml/pad7z9poB1DnJtTPXriFtZQcvKMoK6bLghIo1xNHH42yhnB51Git6qVjRdMQZ/G8Mgg5lNqSNr5YBWtNzubwMm/W/FN50r4SX00i11ycKmmwexjDyrVhjCzgvY0pa+DZ4/6ul2wF3f0B3+zJAq/PFw1oHZ4MnXQrGHb/f4EwbN4Mprzj43Un6ZXnXrGAcJ0JRIUT7t9dVyuzkqiSDCllmv3612rYDpZInoZYTsekrcSc4UU1W5N34rLIfLFAg==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      name: redis-auth
      namespace: databases
    type: Opaque
