---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: redis-auth
  namespace: databases
spec:
  encryptedData:
    redis-password: AgCq4OZZxo5AJCt1OVjMh4cUGNrs6jAFltZi85dMHA/qPDgLvucdMuUrJazt5zAQxHO0Po0dE8iJii1QhS8kq1Qm0KitH9+3PP+X62wThezCoXvTaliC7842BvAd05aqqq4pbj1jJnFgAtiw1Phhy/EyRa8mVxMIUrMTpk5zx88VF5sZb0JW+/SviyISgq7qKVf1fctZgqQgfiWyBRSyFywcWklLNR1lbOctDjr7c6SJ9nzyvkjWCBQAt/OyqMKAEMJNsR6IqzPv0TckhEa+THmvzmlfyF8OLfVK5chR/mCqV9SrhjDzvpPaLHalMEDvKCDKYbFvQp8QbHdZsbKf0toVcxM6ATimkfeHIlthY+MDG7aZY5G+7/gMiHCMbJTGVVDy+hung9G64toSVK+yXl4li3Ctgieehqx4OY6tkHtAA/6BS6D4FJjQoeTF/5Chic3zdaj9FwCET1X4BPfVZySDB5ow5+Fxl9qM8V4/VnTQO7fAxUA4UAXnNB/Y4vBKDLOBOoiV/iWYH6cwLCDOWbjHXGCl5mkSWkEw+5DqFwXuquRRlQxE2wCfh9uEMmg2pIOPWQc5HCv1CZ51l+wScW+kt9qH9QvOWRSy1jy8DAvBsok89UapeTK6Wu35KiHwHf5mlDx8hMNs0w22NvbL61YZX1Z+Jyo4EqqH6fRHlbBN2bwNwPUMysOOJZgsOuL8r/x6lg2K7rucSN+PHZUmHzDN9g3oh01XbCUsCs62W6/nyQ==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      name: redis-auth
      namespace: databases
    type: Opaque
